# Generated by Django 4.2.6 on 2024-04-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_speechrecognitionhistory_speech_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Class Name')),
                ('ClassFee', models.IntegerField(blank=True, default='0', null=True, verbose_name='Total Fee')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Student Full Name')),
                ('ReceivedAmount', models.IntegerField(blank=True, default='0', null=True, verbose_name='Received Amount')),
                ('ReceivedBy', models.CharField(blank=True, max_length=200, null=True, verbose_name='ReceivedBy')),
                ('ParentNumber', models.CharField(blank=True, max_length=14, null=True, verbose_name='Parent Phone Number')),
                ('StatusFee', models.IntegerField(blank=True, default='10', null=True, verbose_name='Status Fee')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('StudentImage', models.ImageField(blank=True, null=True, upload_to='media/StudentImages', verbose_name='Student Image')),
                ('is_finished', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.classes')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.DeleteModel(
            name='SpeechRecognitionHistory',
        ),
    ]
