# Generated by Django 4.2.6 on 2024-04-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_classes_students_delete_speechrecognitionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='AmountRemained',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount Remained'),
        ),
        migrations.AlterField(
            model_name='students',
            name='StatusFee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Paid Amount'),
        ),
    ]
