# Generated by Django 4.2.6 on 2024-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_students_amountremained_alter_students_statusfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='AmountExceed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount Exceed'),
        ),
    ]
