# Generated by Django 4.2.6 on 2024-04-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_students_amountexceed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='AmountExceed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Exceed'),
        ),
        migrations.AlterField(
            model_name='students',
            name='AmountRemained',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Remained'),
        ),
        migrations.AlterField(
            model_name='students',
            name='ReceivedAmount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Received Amount'),
        ),
        migrations.AlterField(
            model_name='students',
            name='StatusFee',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Paid Amount'),
        ),
    ]
