# Generated by Django 4.2.6 on 2024-04-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_students_amountexceed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='ClassFee',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Fee'),
        ),
    ]
