# Generated by Django 4.2.6 on 2024-04-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_students_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='IssuedAmount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Issued Amount'),
        ),
        migrations.AddField(
            model_name='students',
            name='IssuedBy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IssuedBy'),
        ),
        migrations.AddField(
            model_name='students',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
