# Generated by Django 4.2.6 on 2024-05-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_semister_alter_classes_options_students_semister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='students',
            name='AmountExceed_Semister_01',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Exceed Semister 1'),
        ),
        migrations.AddField(
            model_name='students',
            name='AmountExceed_Semister_02',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Exceed Semister 2'),
        ),
        migrations.AddField(
            model_name='students',
            name='AmountExceed_Semister_03',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Exceed Semister 3'),
        ),
        migrations.AddField(
            model_name='students',
            name='AmountRemained_Semister_01',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Remained Semister 1'),
        ),
        migrations.AddField(
            model_name='students',
            name='AmountRemained_Semister_02',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Remained Semister 2'),
        ),
        migrations.AddField(
            model_name='students',
            name='AmountRemained_Semister_03',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Remained Semister 3'),
        ),
        migrations.AddField(
            model_name='students',
            name='StatusFee_Semister_01',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Paid Amount Semister 1'),
        ),
        migrations.AddField(
            model_name='students',
            name='StatusFee_Semister_02',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Paid Amount Semister 2'),
        ),
        migrations.AddField(
            model_name='students',
            name='StatusFee_Semister_03',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Paid Amount Semister 3'),
        ),
        migrations.AddField(
            model_name='students',
            name='is_finished_Semister_01',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='is_finished_Semister_02',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='is_finished_Semister_03',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
