# Generated by Django 4.2.6 on 2024-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_years_students_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='Level',
            field=models.CharField(blank=True, choices=[(' ', 'Chooces Level'), ('Primary Level', 'Primary Level'), ('O-Level', 'O-Level')], max_length=200, null=True, verbose_name='Level'),
        ),
    ]
